# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x89\x02\n\x0c_TestRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\"\n\x08\x63reateIO\x18\x02 \x01(\x0b\x32\x0e._TestCreateIOH\x00\x12&\n\nsetIOValue\x18\x03 \x01(\x0b\x32\x10._TestSetIOValueH\x00\x12&\n\ngetIOValue\x18\x04 \x01(\x0b\x32\x10._TestGetIOValueH\x00\x12\"\n\x08\x63learIOs\x18\x05 \x01(\x0b\x32\x0e._TestClearIOSH\x00\x12&\n\nmemoryFree\x18\x06 \x01(\x0b\x32\x10._TestMemoryFreeH\x00\x12\"\n\x08resetAPI\x18\x07 \x01(\x0b\x32\x0e._TestResetAPIH\x00\x42\t\n\x07message\"t\n\x12_TestResponseValue\x12\x13\n\tboolValue\x18\x02 \x01(\x08H\x00\x12\x12\n\x08intValue\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x64oubleValue\x18\x04 \x01(\x02H\x00\x12\x15\n\x0bstringValue\x18\x05 \x01(\tH\x00\x42\x07\n\x05value\"P\n\r_TestResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12$\n\x07message\x18\x02 \x01(\x0b\x32\x13._TestResponseValue\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\"\x1c\n\r_TestCreateIO\x12\x0b\n\x03pin\x18\x01 \x01(\r\"-\n\x0f_TestSetIOValue\x12\x0b\n\x03pin\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"\x1e\n\x0f_TestGetIOValue\x12\x0b\n\x03pin\x18\x01 \x01(\r\"\x0f\n\r_TestClearIOS\"\x11\n\x0f_TestMemoryFree\"\x0f\n\r_TestResetAPIb\x06proto3')



__TESTREQUEST = DESCRIPTOR.message_types_by_name['_TestRequest']
__TESTRESPONSEVALUE = DESCRIPTOR.message_types_by_name['_TestResponseValue']
__TESTRESPONSE = DESCRIPTOR.message_types_by_name['_TestResponse']
__TESTCREATEIO = DESCRIPTOR.message_types_by_name['_TestCreateIO']
__TESTSETIOVALUE = DESCRIPTOR.message_types_by_name['_TestSetIOValue']
__TESTGETIOVALUE = DESCRIPTOR.message_types_by_name['_TestGetIOValue']
__TESTCLEARIOS = DESCRIPTOR.message_types_by_name['_TestClearIOS']
__TESTMEMORYFREE = DESCRIPTOR.message_types_by_name['_TestMemoryFree']
__TESTRESETAPI = DESCRIPTOR.message_types_by_name['_TestResetAPI']
_TestRequest = _reflection.GeneratedProtocolMessageType('_TestRequest', (_message.Message,), {
  'DESCRIPTOR' : __TESTREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestRequest)
  })
_sym_db.RegisterMessage(_TestRequest)

_TestResponseValue = _reflection.GeneratedProtocolMessageType('_TestResponseValue', (_message.Message,), {
  'DESCRIPTOR' : __TESTRESPONSEVALUE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestResponseValue)
  })
_sym_db.RegisterMessage(_TestResponseValue)

_TestResponse = _reflection.GeneratedProtocolMessageType('_TestResponse', (_message.Message,), {
  'DESCRIPTOR' : __TESTRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestResponse)
  })
_sym_db.RegisterMessage(_TestResponse)

_TestCreateIO = _reflection.GeneratedProtocolMessageType('_TestCreateIO', (_message.Message,), {
  'DESCRIPTOR' : __TESTCREATEIO,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestCreateIO)
  })
_sym_db.RegisterMessage(_TestCreateIO)

_TestSetIOValue = _reflection.GeneratedProtocolMessageType('_TestSetIOValue', (_message.Message,), {
  'DESCRIPTOR' : __TESTSETIOVALUE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestSetIOValue)
  })
_sym_db.RegisterMessage(_TestSetIOValue)

_TestGetIOValue = _reflection.GeneratedProtocolMessageType('_TestGetIOValue', (_message.Message,), {
  'DESCRIPTOR' : __TESTGETIOVALUE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestGetIOValue)
  })
_sym_db.RegisterMessage(_TestGetIOValue)

_TestClearIOS = _reflection.GeneratedProtocolMessageType('_TestClearIOS', (_message.Message,), {
  'DESCRIPTOR' : __TESTCLEARIOS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestClearIOS)
  })
_sym_db.RegisterMessage(_TestClearIOS)

_TestMemoryFree = _reflection.GeneratedProtocolMessageType('_TestMemoryFree', (_message.Message,), {
  'DESCRIPTOR' : __TESTMEMORYFREE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestMemoryFree)
  })
_sym_db.RegisterMessage(_TestMemoryFree)

_TestResetAPI = _reflection.GeneratedProtocolMessageType('_TestResetAPI', (_message.Message,), {
  'DESCRIPTOR' : __TESTRESETAPI,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:_TestResetAPI)
  })
_sym_db.RegisterMessage(_TestResetAPI)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  __TESTREQUEST._serialized_start=15
  __TESTREQUEST._serialized_end=280
  __TESTRESPONSEVALUE._serialized_start=282
  __TESTRESPONSEVALUE._serialized_end=398
  __TESTRESPONSE._serialized_start=400
  __TESTRESPONSE._serialized_end=480
  __TESTCREATEIO._serialized_start=482
  __TESTCREATEIO._serialized_end=510
  __TESTSETIOVALUE._serialized_start=512
  __TESTSETIOVALUE._serialized_end=557
  __TESTGETIOVALUE._serialized_start=559
  __TESTGETIOVALUE._serialized_end=589
  __TESTCLEARIOS._serialized_start=591
  __TESTCLEARIOS._serialized_end=606
  __TESTMEMORYFREE._serialized_start=608
  __TESTMEMORYFREE._serialized_end=625
  __TESTRESETAPI._serialized_start=627
  __TESTRESETAPI._serialized_end=642
# @@protoc_insertion_point(module_scope)
