/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "test.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(_TestRequest, _TestRequest, AUTO)


PB_BIND(_TestResponseValue, _TestResponseValue, AUTO)


PB_BIND(_TestResponse, _TestResponse, AUTO)


PB_BIND(_TestCreateIO, _TestCreateIO, AUTO)


PB_BIND(_TestSetIOValue, _TestSetIOValue, AUTO)


PB_BIND(_TestGetIOValue, _TestGetIOValue, AUTO)


PB_BIND(_TestClearIOS, _TestClearIOS, AUTO)


PB_BIND(_TestFreeMemory, _TestFreeMemory, AUTO)


PB_BIND(_TestSetClockOffset, _TestSetClockOffset, AUTO)


PB_BIND(_TestGetMillis, _TestGetMillis, AUTO)


PB_BIND(_TestSetIOSource, _TestSetIOSource, AUTO)


PB_BIND(_TestLoadAPIFromEEPROM, _TestLoadAPIFromEEPROM, AUTO)


PB_BIND(_TestResetClock, _TestResetClock, AUTO)





