/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_TEST_PB_H_INCLUDED
#define PB_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum __TestCreateIO_IOType { 
    _TestCreateIO_IOType_DIGITAL = 0, 
    _TestCreateIO_IOType_ANALOGIC = 1 
} _TestCreateIO_IOType;

/* Struct definitions */
typedef struct __TestClearIOS { 
    char dummy_field;
} _TestClearIOS;

typedef struct __TestFreeMemory { 
    char dummy_field;
} _TestFreeMemory;

typedef struct __TestGetMillis { 
    char dummy_field;
} _TestGetMillis;

typedef struct __TestResetAPI { 
    char dummy_field;
} _TestResetAPI;

typedef struct __TestCreateIO { 
    uint32_t pin; 
    _TestCreateIO_IOType type; 
} _TestCreateIO;

typedef struct __TestGetIOValue { 
    uint32_t pin; 
} _TestGetIOValue;

typedef struct __TestResponseValue { 
    pb_size_t which_value;
    union {
        bool boolValue;
        int32_t intValue;
        uint32_t uintValue;
        float doubleValue;
        char stringValue[100];
    } value; 
} _TestResponseValue;

typedef struct __TestSetClockOffset { 
    uint32_t value; 
} _TestSetClockOffset;

typedef struct __TestSetIOValue { 
    uint32_t pin; 
    uint32_t value; 
} _TestSetIOValue;

typedef struct __TestRequest { 
    uint32_t id; 
    pb_size_t which_message;
    union {
        _TestCreateIO createIO;
        _TestSetIOValue setIOValue;
        _TestGetIOValue getIOValue;
        _TestClearIOS clearIOs;
        _TestFreeMemory freeMemory;
        _TestSetClockOffset setClockOffset;
        _TestGetMillis getMillis;
        _TestResetAPI resetAPI;
    } message; 
} _TestRequest;

typedef struct __TestResponse { 
    uint64_t id; 
    bool has_message;
    _TestResponseValue message; 
    bool error; 
} _TestResponse;


/* Helper constants for enums */
#define __TestCreateIO_IOType_MIN _TestCreateIO_IOType_DIGITAL
#define __TestCreateIO_IOType_MAX _TestCreateIO_IOType_ANALOGIC
#define __TestCreateIO_IOType_ARRAYSIZE ((_TestCreateIO_IOType)(_TestCreateIO_IOType_ANALOGIC+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define _TestRequest_init_default                {0, 0, {_TestCreateIO_init_default}}
#define _TestResponseValue_init_default          {0, {0}}
#define _TestResponse_init_default               {0, false, _TestResponseValue_init_default, 0}
#define _TestCreateIO_init_default               {0, __TestCreateIO_IOType_MIN}
#define _TestSetIOValue_init_default             {0, 0}
#define _TestGetIOValue_init_default             {0}
#define _TestClearIOS_init_default               {0}
#define _TestFreeMemory_init_default             {0}
#define _TestSetClockOffset_init_default         {0}
#define _TestGetMillis_init_default              {0}
#define _TestResetAPI_init_default               {0}
#define _TestRequest_init_zero                   {0, 0, {_TestCreateIO_init_zero}}
#define _TestResponseValue_init_zero             {0, {0}}
#define _TestResponse_init_zero                  {0, false, _TestResponseValue_init_zero, 0}
#define _TestCreateIO_init_zero                  {0, __TestCreateIO_IOType_MIN}
#define _TestSetIOValue_init_zero                {0, 0}
#define _TestGetIOValue_init_zero                {0}
#define _TestClearIOS_init_zero                  {0}
#define _TestFreeMemory_init_zero                {0}
#define _TestSetClockOffset_init_zero            {0}
#define _TestGetMillis_init_zero                 {0}
#define _TestResetAPI_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define _TestCreateIO_pin_tag                    1
#define _TestCreateIO_type_tag                   2
#define _TestGetIOValue_pin_tag                  1
#define _TestResponseValue_boolValue_tag         2
#define _TestResponseValue_intValue_tag          3
#define _TestResponseValue_uintValue_tag         4
#define _TestResponseValue_doubleValue_tag       5
#define _TestResponseValue_stringValue_tag       6
#define _TestSetClockOffset_value_tag            1
#define _TestSetIOValue_pin_tag                  1
#define _TestSetIOValue_value_tag                2
#define _TestRequest_id_tag                      1
#define _TestRequest_createIO_tag                2
#define _TestRequest_setIOValue_tag              3
#define _TestRequest_getIOValue_tag              4
#define _TestRequest_clearIOs_tag                5
#define _TestRequest_freeMemory_tag              6
#define _TestRequest_setClockOffset_tag          7
#define _TestRequest_getMillis_tag               8
#define _TestRequest_resetAPI_tag                9
#define _TestResponse_id_tag                     1
#define _TestResponse_message_tag                2
#define _TestResponse_error_tag                  3

/* Struct field encoding specification for nanopb */
#define _TestRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,createIO,message.createIO),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,setIOValue,message.setIOValue),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,getIOValue,message.getIOValue),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,clearIOs,message.clearIOs),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,freeMemory,message.freeMemory),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,setClockOffset,message.setClockOffset),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,getMillis,message.getMillis),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,resetAPI,message.resetAPI),   9)
#define _TestRequest_CALLBACK NULL
#define _TestRequest_DEFAULT NULL
#define _TestRequest_message_createIO_MSGTYPE _TestCreateIO
#define _TestRequest_message_setIOValue_MSGTYPE _TestSetIOValue
#define _TestRequest_message_getIOValue_MSGTYPE _TestGetIOValue
#define _TestRequest_message_clearIOs_MSGTYPE _TestClearIOS
#define _TestRequest_message_freeMemory_MSGTYPE _TestFreeMemory
#define _TestRequest_message_setClockOffset_MSGTYPE _TestSetClockOffset
#define _TestRequest_message_getMillis_MSGTYPE _TestGetMillis
#define _TestRequest_message_resetAPI_MSGTYPE _TestResetAPI

#define _TestResponseValue_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolValue,value.boolValue),   2) \
X(a, STATIC,   ONEOF,    INT32,    (value,intValue,value.intValue),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (value,uintValue,value.uintValue),   4) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,doubleValue,value.doubleValue),   5) \
X(a, STATIC,   ONEOF,    STRING,   (value,stringValue,value.stringValue),   6)
#define _TestResponseValue_CALLBACK NULL
#define _TestResponseValue_DEFAULT NULL

#define _TestResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           2) \
X(a, STATIC,   SINGULAR, BOOL,     error,             3)
#define _TestResponse_CALLBACK NULL
#define _TestResponse_DEFAULT NULL
#define _TestResponse_message_MSGTYPE _TestResponseValue

#define _TestCreateIO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define _TestCreateIO_CALLBACK NULL
#define _TestCreateIO_DEFAULT NULL

#define _TestSetIOValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define _TestSetIOValue_CALLBACK NULL
#define _TestSetIOValue_DEFAULT NULL

#define _TestGetIOValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               1)
#define _TestGetIOValue_CALLBACK NULL
#define _TestGetIOValue_DEFAULT NULL

#define _TestClearIOS_FIELDLIST(X, a) \

#define _TestClearIOS_CALLBACK NULL
#define _TestClearIOS_DEFAULT NULL

#define _TestFreeMemory_FIELDLIST(X, a) \

#define _TestFreeMemory_CALLBACK NULL
#define _TestFreeMemory_DEFAULT NULL

#define _TestSetClockOffset_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define _TestSetClockOffset_CALLBACK NULL
#define _TestSetClockOffset_DEFAULT NULL

#define _TestGetMillis_FIELDLIST(X, a) \

#define _TestGetMillis_CALLBACK NULL
#define _TestGetMillis_DEFAULT NULL

#define _TestResetAPI_FIELDLIST(X, a) \

#define _TestResetAPI_CALLBACK NULL
#define _TestResetAPI_DEFAULT NULL

extern const pb_msgdesc_t _TestRequest_msg;
extern const pb_msgdesc_t _TestResponseValue_msg;
extern const pb_msgdesc_t _TestResponse_msg;
extern const pb_msgdesc_t _TestCreateIO_msg;
extern const pb_msgdesc_t _TestSetIOValue_msg;
extern const pb_msgdesc_t _TestGetIOValue_msg;
extern const pb_msgdesc_t _TestClearIOS_msg;
extern const pb_msgdesc_t _TestFreeMemory_msg;
extern const pb_msgdesc_t _TestSetClockOffset_msg;
extern const pb_msgdesc_t _TestGetMillis_msg;
extern const pb_msgdesc_t _TestResetAPI_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define _TestRequest_fields &_TestRequest_msg
#define _TestResponseValue_fields &_TestResponseValue_msg
#define _TestResponse_fields &_TestResponse_msg
#define _TestCreateIO_fields &_TestCreateIO_msg
#define _TestSetIOValue_fields &_TestSetIOValue_msg
#define _TestGetIOValue_fields &_TestGetIOValue_msg
#define _TestClearIOS_fields &_TestClearIOS_msg
#define _TestFreeMemory_fields &_TestFreeMemory_msg
#define _TestSetClockOffset_fields &_TestSetClockOffset_msg
#define _TestGetMillis_fields &_TestGetMillis_msg
#define _TestResetAPI_fields &_TestResetAPI_msg

/* Maximum encoded size of messages (where known) */
#define _TestClearIOS_size                       0
#define _TestCreateIO_size                       8
#define _TestFreeMemory_size                     0
#define _TestGetIOValue_size                     6
#define _TestGetMillis_size                      0
#define _TestRequest_size                        20
#define _TestResetAPI_size                       0
#define _TestResponseValue_size                  101
#define _TestResponse_size                       116
#define _TestSetClockOffset_size                 6
#define _TestSetIOValue_size                     12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
